version: '3'
services:
  frontend:
    build: ./eventhub-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./eventhub-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  backend:
    build: ./eventhub-backend
    ports:
      - "4000:4000"
    volumes:
      - ./eventhub-backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://user:password@db:5432/mydb
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
