version: '3'
services:
  frontend:
    build: ./eventhub-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./eventhub-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
